resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/mikeymc/spring-react-starter.git
      branch: master
jobs:
- name: java
  plan:
  - get: repo
  - task: test
    file: repo/java_test.yml